import {
  LayoutDashboard,
  CalendarCheck,
  FileText,
  Ticket,
  Briefcase,
  Users,
  Megaphone,
  UserCircle,
  Settings,
  BookOpen,
  UserCheck,
  Building2,
  GraduationCap,
  BarChart3,
  ScrollText,
} from "lucide-react";

// each role sees a different set of sidebar tabs — this is the single
// source of truth the dashboard shell reads from to build the menu
export const roleNavConfig = {
  student: [
    { label: "Overview", path: "", icon: LayoutDashboard },
    { label: "Attendance", path: "attendance", icon: CalendarCheck },
    { label: "Assignments", path: "assignments", icon: FileText },
    { label: "Events", path: "events", icon: Ticket },
    { label: "Placements", path: "placements", icon: Briefcase },
    { label: "Clubs", path: "clubs", icon: Users },
    { label: "Notices", path: "notices", icon: Megaphone },
    { label: "Profile", path: "profile", icon: UserCircle },
    { label: "Settings", path: "settings", icon: Settings },
  ],
  faculty: [
    { label: "Overview", path: "", icon: LayoutDashboard },
    { label: "Classes", path: "classes", icon: BookOpen },
    { label: "Attendance", path: "attendance", icon: CalendarCheck },
    { label: "Assignments", path: "assignments", icon: FileText },
    { label: "Notices", path: "notices", icon: Megaphone },
    { label: "Profile", path: "profile", icon: UserCircle },
    { label: "Settings", path: "settings", icon: Settings },
  ],
  coordinator: [
    { label: "Overview", path: "", icon: LayoutDashboard },
    { label: "Events", path: "events", icon: Ticket },
    { label: "Clubs", path: "clubs", icon: Users },
    { label: "Approvals", path: "approvals", icon: UserCheck },
    { label: "Notices", path: "notices", icon: Megaphone },
    { label: "Profile", path: "profile", icon: UserCircle },
    { label: "Settings", path: "settings", icon: Settings },
  ],
  admin: [
    { label: "Overview", path: "", icon: LayoutDashboard },
    { label: "Users", path: "users", icon: Users },
    { label: "Departments", path: "departments", icon: Building2 },
    { label: "Courses", path: "courses", icon: GraduationCap },
    { label: "Events", path: "events", icon: Ticket },
    { label: "Attendance", path: "attendance", icon: CalendarCheck },
    { label: "Placements", path: "placements", icon: Briefcase },
    { label: "Announcements", path: "announcements", icon: Megaphone },
    { label: "Reports", path: "reports", icon: BarChart3 },
    { label: "Logs", path: "logs", icon: ScrollText },
    { label: "Settings", path: "settings", icon: Settings },
  ],
};
